# Generated by Django 5.0.6 on 2024-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.PositiveBigIntegerField(default=0, verbose_name='وزن'),
        ),
    ]
